# Generated by Django 4.1.1 on 2022-11-11 00:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_area_covered_alter_listing_bathrooms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='maps',
            field=models.URLField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
