# Generated by Django 4.1.1 on 2022-11-11 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='maps',
        ),
    ]
