# Generated by Django 4.1.1 on 2022-11-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='seller',
            name='message',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
