# Generated by Django 4.1.1 on 2022-11-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_alter_seller_email_alter_seller_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='location',
            field=models.CharField(default='nolocation', max_length=25),
        ),
    ]
