# Generated by Django 4.1.1 on 2022-11-12 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_seller_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='seller',
            name='location',
            field=models.CharField(default='1', max_length=25),
        ),
    ]
